FROM node:20-bookworm-slim

WORKDIR /app

COPY visualizer/package.json visualizer/package-lock.json /app/
RUN npm ci

COPY visualizer /app

ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start", "--", "--hostname", "0.0.0.0", "--port", "3000"]
